# Generated by Django 5.1 on 2024-09-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_zarinpal_authority_alter_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zarinpal_data',
            field=models.TextField(blank=True, verbose_name='zarinpal_data'),
        ),
        migrations.AddField(
            model_name='order',
            name='zarinpal_ref_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ref_id'),
        ),
    ]
