# Generated by Django 5.1 on 2024-09-02 14:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='specialty',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Specialty'),
        ),
    ]
